/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static java.lang.Thread.sleep;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ELEE
 */
public class ColorGameGUI extends javax.swing.JFrame {

    
    static int finalScore;
    private EndScreen endScreen;
    private PlayScreenGUI playScreen;
    /**
     * Creates new form ColorGameGUI
     */
    public ColorGameGUI(int finalScore) {
        
        this.finalScore = finalScore;
        endScreen = new EndScreen(finalScore);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateTime = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        redBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 110, 100, 40);

        dateTime.setText("Date and Time");
        getContentPane().add(dateTime);
        dateTime.setBounds(430, 30, 150, 20);

        title.setText("Color Game");
        getContentPane().add(title);
        title.setBounds(430, 10, 90, 20);

        redBtn.setBackground(new java.awt.Color(255, 255, 255));
        redBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redSplat.png"))); // NOI18N
        getContentPane().add(redBtn);
        redBtn.setBounds(440, 269, 80, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorGameGUI(finalScore).setVisible(true);
            }
        });
    }
    
    // method: getFinalScore
    // purpose: return the final score 
    public int getFinalScore() {
        return finalScore;
    }
    
    // method: endGame
    // purpose: change the visibility of the play screen as false and
    // show the end screen
    public void endGame() {
        this.setVisible(false);
        endScreen.setScore(getFinalScore());
        endScreen.setVisible(true);
    }
    
    public void setScore(int finalScore) {
        String displayScore = Integer.toString(finalScore);
        //scoreLabel.setText(displayScore);
    }
    
    // method: displayDateTime
    // purpose: display current time and date. Update each second.
    public void displayDateTime() {
       
        Thread currentTime = new Thread() {
            public void run() {
                for(;;) {
                    DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                    Date dateObject = new Date();
                    dateTime.setText(dateFormat.format(dateObject));
                    try {
                        sleep(1000);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        currentTime.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton redBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
