package gui;

/***************************************************************
* file: HighScoreGUI.java
* author: Hagop Bowazoglanian
*         John Vincent Canalita
*         Eugene Lee
*         Seungyun Lee
*         Dylan Nguyen
* 
* Class: CS 245 – Programming Graphical User Interfaces
*
* assignment: program 1.0
* date last modified: 1/16/2017
*
* purpose: Creates the High Score GUI for the Hangman game,
*          showing the high scores of the game with its player 
*
****************************************************************/
public class HighScoreGUI extends javax.swing.JFrame {
    
    // method: HighScoreGUI
    // purpose: constructor for the class
    public HighScoreGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        highScore1 = new javax.swing.JLabel();
        highScore2 = new javax.swing.JLabel();
        highScore3 = new javax.swing.JLabel();
        highScore4 = new javax.swing.JLabel();
        highScore5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        title.setText("HIGHSCORES");
        title.setPreferredSize(new java.awt.Dimension(170, 35));
        getContentPane().add(title);
        title.setBounds(215, 50, 170, 35);

        highScore1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        highScore1.setText("ABC.....00000");
        highScore1.setPreferredSize(new java.awt.Dimension(86, 16));
        getContentPane().add(highScore1);
        highScore1.setBounds(257, 100, 86, 16);

        highScore2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        highScore2.setText("ABC.....00000");
        highScore2.setPreferredSize(new java.awt.Dimension(86, 16));
        getContentPane().add(highScore2);
        highScore2.setBounds(257, 130, 86, 16);

        highScore3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        highScore3.setText("ABC.....00000");
        highScore3.setPreferredSize(new java.awt.Dimension(86, 16));
        getContentPane().add(highScore3);
        highScore3.setBounds(257, 160, 86, 16);

        highScore4.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        highScore4.setText("ABC.....00000");
        highScore4.setPreferredSize(new java.awt.Dimension(86, 16));
        getContentPane().add(highScore4);
        highScore4.setBounds(257, 190, 86, 16);

        highScore5.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        highScore5.setText("ABC.....00000");
        highScore5.setPreferredSize(new java.awt.Dimension(86, 16));
        getContentPane().add(highScore5);
        highScore5.setBounds(257, 220, 86, 16);

        backButton.setText("Back");
        backButton.setPreferredSize(new java.awt.Dimension(75, 33));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(3, 335, 75, 33);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // method: backButtonActionPerformed
    // purpose: disables the current screen and enables the menu screen
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new MenuGUI().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    // method: main
    // purpose: runs the current screen on its own
    public static void main(String args[]) {
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScoreGUI().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel highScore1;
    private javax.swing.JLabel highScore2;
    private javax.swing.JLabel highScore3;
    private javax.swing.JLabel highScore4;
    private javax.swing.JLabel highScore5;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
