/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.ColorGameGUI.finalScore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import other.Info;
import java.lang.*;

/**
 *
 * @author hagop_000
 */
public class SudokuGUI extends javax.swing.JFrame {

    //public static final int GRID_SIZE = 9;    // Size of the board
    //public static final int SUBGRID_SIZE = 3; // Size of the sub-grid
    //static int finalScore;
    
    //static int max = 9;
    //static int min = 1;
    
    // The game board composes of 9x9 JTextFields,
    // each containing String "1" to "9", or empty String
    //private JTextField[][] tfCells = new JTextField[GRID_SIZE][GRID_SIZE];
    
    static int [][] a = new int [9][9];
    
    /**
     * Creates new form SudokuGUI
     */
    public SudokuGUI(int finalScore) {
        
        // Shows Info Frame when F1 is pressed
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_F1,0), "Info");
        getRootPane().getActionMap().put("Info", new AbstractAction(){ //$NON-NLS-1$
            @Override
            public void actionPerformed(ActionEvent e)
            {
                Info info = new Info();
            }
        });
        
        // Exits program when ESC key is pressed
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0), "Exit");
        getRootPane().getActionMap().put("Exit", new AbstractAction(){ //$NON-NLS-1$
            @Override
            public void actionPerformed(ActionEvent e)
            {
                System.exit(0);
            }
        });
        
        displayDateTimeSudoku();
        initComponents();
        generate();
        setupSudoku();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        dateTime = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        btn00 = new javax.swing.JTextField();
        btn01 = new javax.swing.JTextField();
        btn02 = new javax.swing.JTextField();
        btn03 = new javax.swing.JTextField();
        btn04 = new javax.swing.JTextField();
        btn05 = new javax.swing.JTextField();
        btn06 = new javax.swing.JTextField();
        btn07 = new javax.swing.JTextField();
        btn08 = new javax.swing.JTextField();
        btn10 = new javax.swing.JTextField();
        btn11 = new javax.swing.JTextField();
        btn12 = new javax.swing.JTextField();
        btn13 = new javax.swing.JTextField();
        btn14 = new javax.swing.JTextField();
        btn15 = new javax.swing.JTextField();
        btn16 = new javax.swing.JTextField();
        btn17 = new javax.swing.JTextField();
        btn18 = new javax.swing.JTextField();
        btn20 = new javax.swing.JTextField();
        btn21 = new javax.swing.JTextField();
        btn22 = new javax.swing.JTextField();
        btn23 = new javax.swing.JTextField();
        btn24 = new javax.swing.JTextField();
        btn25 = new javax.swing.JTextField();
        btn26 = new javax.swing.JTextField();
        btn27 = new javax.swing.JTextField();
        btn28 = new javax.swing.JTextField();
        btn30 = new javax.swing.JTextField();
        btn31 = new javax.swing.JTextField();
        btn32 = new javax.swing.JTextField();
        btn33 = new javax.swing.JTextField();
        btn34 = new javax.swing.JTextField();
        btn35 = new javax.swing.JTextField();
        btn36 = new javax.swing.JTextField();
        btn37 = new javax.swing.JTextField();
        btn38 = new javax.swing.JTextField();
        btn40 = new javax.swing.JTextField();
        btn41 = new javax.swing.JTextField();
        btn42 = new javax.swing.JTextField();
        btn43 = new javax.swing.JTextField();
        btn44 = new javax.swing.JTextField();
        btn45 = new javax.swing.JTextField();
        btn46 = new javax.swing.JTextField();
        btn47 = new javax.swing.JTextField();
        btn48 = new javax.swing.JTextField();
        btn50 = new javax.swing.JTextField();
        btn51 = new javax.swing.JTextField();
        btn52 = new javax.swing.JTextField();
        btn53 = new javax.swing.JTextField();
        btn54 = new javax.swing.JTextField();
        btn55 = new javax.swing.JTextField();
        btn56 = new javax.swing.JTextField();
        btn57 = new javax.swing.JTextField();
        btn58 = new javax.swing.JTextField();
        btn60 = new javax.swing.JTextField();
        btn61 = new javax.swing.JTextField();
        btn62 = new javax.swing.JTextField();
        btn63 = new javax.swing.JTextField();
        btn64 = new javax.swing.JTextField();
        btn65 = new javax.swing.JTextField();
        btn66 = new javax.swing.JTextField();
        btn67 = new javax.swing.JTextField();
        btn68 = new javax.swing.JTextField();
        btn70 = new javax.swing.JTextField();
        btn71 = new javax.swing.JTextField();
        btn72 = new javax.swing.JTextField();
        btn73 = new javax.swing.JTextField();
        btn74 = new javax.swing.JTextField();
        btn75 = new javax.swing.JTextField();
        btn76 = new javax.swing.JTextField();
        btn77 = new javax.swing.JTextField();
        btn78 = new javax.swing.JTextField();
        btn80 = new javax.swing.JTextField();
        btn81 = new javax.swing.JTextField();
        btn82 = new javax.swing.JTextField();
        btn83 = new javax.swing.JTextField();
        btn84 = new javax.swing.JTextField();
        btn85 = new javax.swing.JTextField();
        btn86 = new javax.swing.JTextField();
        btn87 = new javax.swing.JTextField();
        btn88 = new javax.swing.JTextField();
        jLabel00 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        scoreLabel.setText("Score");
        getContentPane().add(scoreLabel);
        scoreLabel.setBounds(440, 60, 34, 16);

        title.setText("Sudoku");
        title.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(title);
        title.setBounds(440, 20, 79, 20);

        dateTime.setText("Date and Time");
        getContentPane().add(dateTime);
        dateTime.setBounds(440, 40, 140, 16);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(460, 320, 75, 33);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton);
        quitButton.setBounds(460, 270, 75, 33);

        btn00.setBackground(java.awt.Color.black);
        btn00.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn00.setBorder(null);
        btn00.setMaximumSize(new java.awt.Dimension(40, 40));
        btn00.setMinimumSize(new java.awt.Dimension(40, 40));
        btn00.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn00);
        btn00.setBounds(50, 10, 40, 40);

        btn01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn01.setBorder(null);
        btn01.setMaximumSize(new java.awt.Dimension(40, 40));
        btn01.setMinimumSize(new java.awt.Dimension(40, 40));
        btn01.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn01);
        btn01.setBounds(50, 50, 40, 40);

        btn02.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn02.setBorder(null);
        btn02.setMaximumSize(new java.awt.Dimension(40, 40));
        btn02.setMinimumSize(new java.awt.Dimension(40, 40));
        btn02.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn02);
        btn02.setBounds(50, 90, 40, 40);

        btn03.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn03.setBorder(null);
        btn03.setMaximumSize(new java.awt.Dimension(40, 40));
        btn03.setMinimumSize(new java.awt.Dimension(40, 40));
        btn03.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn03);
        btn03.setBounds(50, 130, 40, 40);

        btn04.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn04.setBorder(null);
        btn04.setMaximumSize(new java.awt.Dimension(40, 40));
        btn04.setMinimumSize(new java.awt.Dimension(40, 40));
        btn04.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn04);
        btn04.setBounds(50, 170, 40, 40);

        btn05.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn05.setBorder(null);
        btn05.setMaximumSize(new java.awt.Dimension(40, 40));
        btn05.setMinimumSize(new java.awt.Dimension(40, 40));
        btn05.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn05);
        btn05.setBounds(50, 210, 40, 40);

        btn06.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn06.setBorder(null);
        btn06.setMaximumSize(new java.awt.Dimension(40, 40));
        btn06.setMinimumSize(new java.awt.Dimension(40, 40));
        btn06.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn06);
        btn06.setBounds(50, 250, 40, 40);

        btn07.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn07.setBorder(null);
        btn07.setMaximumSize(new java.awt.Dimension(40, 40));
        btn07.setMinimumSize(new java.awt.Dimension(40, 40));
        btn07.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn07);
        btn07.setBounds(50, 290, 40, 40);

        btn08.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn08.setBorder(null);
        btn08.setMaximumSize(new java.awt.Dimension(40, 40));
        btn08.setMinimumSize(new java.awt.Dimension(40, 40));
        btn08.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn08);
        btn08.setBounds(50, 330, 40, 40);

        btn10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn10.setBorder(null);
        btn10.setMaximumSize(new java.awt.Dimension(40, 40));
        btn10.setMinimumSize(new java.awt.Dimension(40, 40));
        btn10.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn10);
        btn10.setBounds(90, 10, 40, 40);

        btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn11.setBorder(null);
        btn11.setMaximumSize(new java.awt.Dimension(40, 40));
        btn11.setMinimumSize(new java.awt.Dimension(40, 40));
        btn11.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn11);
        btn11.setBounds(90, 50, 40, 40);

        btn12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn12.setBorder(null);
        btn12.setMaximumSize(new java.awt.Dimension(40, 40));
        btn12.setMinimumSize(new java.awt.Dimension(40, 40));
        btn12.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn12);
        btn12.setBounds(90, 90, 40, 40);

        btn13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn13.setBorder(null);
        btn13.setMaximumSize(new java.awt.Dimension(40, 40));
        btn13.setMinimumSize(new java.awt.Dimension(40, 40));
        btn13.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn13);
        btn13.setBounds(90, 130, 40, 40);

        btn14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn14.setBorder(null);
        btn14.setMaximumSize(new java.awt.Dimension(40, 40));
        btn14.setMinimumSize(new java.awt.Dimension(40, 40));
        btn14.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn14);
        btn14.setBounds(90, 170, 40, 40);

        btn15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn15.setBorder(null);
        btn15.setMaximumSize(new java.awt.Dimension(40, 40));
        btn15.setMinimumSize(new java.awt.Dimension(40, 40));
        btn15.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn15);
        btn15.setBounds(90, 210, 40, 40);

        btn16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn16.setBorder(null);
        btn16.setMaximumSize(new java.awt.Dimension(40, 40));
        btn16.setMinimumSize(new java.awt.Dimension(40, 40));
        btn16.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn16);
        btn16.setBounds(90, 250, 40, 40);

        btn17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn17.setBorder(null);
        btn17.setMaximumSize(new java.awt.Dimension(40, 40));
        btn17.setMinimumSize(new java.awt.Dimension(40, 40));
        btn17.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn17);
        btn17.setBounds(90, 290, 40, 40);

        btn18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn18.setBorder(null);
        btn18.setMaximumSize(new java.awt.Dimension(40, 40));
        btn18.setMinimumSize(new java.awt.Dimension(40, 40));
        btn18.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn18);
        btn18.setBounds(90, 330, 40, 40);

        btn20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn20.setBorder(null);
        btn20.setMaximumSize(new java.awt.Dimension(40, 40));
        btn20.setMinimumSize(new java.awt.Dimension(40, 40));
        btn20.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn20);
        btn20.setBounds(130, 10, 40, 40);

        btn21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn21.setBorder(null);
        btn21.setMaximumSize(new java.awt.Dimension(40, 40));
        btn21.setMinimumSize(new java.awt.Dimension(40, 40));
        btn21.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn21);
        btn21.setBounds(130, 50, 40, 40);

        btn22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn22.setBorder(null);
        btn22.setMaximumSize(new java.awt.Dimension(40, 40));
        btn22.setMinimumSize(new java.awt.Dimension(40, 40));
        btn22.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn22);
        btn22.setBounds(130, 90, 40, 40);

        btn23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn23.setBorder(null);
        btn23.setMaximumSize(new java.awt.Dimension(40, 40));
        btn23.setMinimumSize(new java.awt.Dimension(40, 40));
        btn23.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn23);
        btn23.setBounds(130, 130, 40, 40);

        btn24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn24.setBorder(null);
        btn24.setMaximumSize(new java.awt.Dimension(40, 40));
        btn24.setMinimumSize(new java.awt.Dimension(40, 40));
        btn24.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn24);
        btn24.setBounds(130, 170, 40, 40);

        btn25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn25.setBorder(null);
        btn25.setMaximumSize(new java.awt.Dimension(40, 40));
        btn25.setMinimumSize(new java.awt.Dimension(40, 40));
        btn25.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn25);
        btn25.setBounds(130, 210, 40, 40);

        btn26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn26.setBorder(null);
        btn26.setMaximumSize(new java.awt.Dimension(40, 40));
        btn26.setMinimumSize(new java.awt.Dimension(40, 40));
        btn26.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn26);
        btn26.setBounds(130, 250, 40, 40);

        btn27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn27.setBorder(null);
        btn27.setMaximumSize(new java.awt.Dimension(40, 40));
        btn27.setMinimumSize(new java.awt.Dimension(40, 40));
        btn27.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn27);
        btn27.setBounds(130, 290, 40, 40);

        btn28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn28.setBorder(null);
        btn28.setMaximumSize(new java.awt.Dimension(40, 40));
        btn28.setMinimumSize(new java.awt.Dimension(40, 40));
        btn28.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn28);
        btn28.setBounds(130, 330, 40, 40);

        btn30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn30.setBorder(null);
        btn30.setMaximumSize(new java.awt.Dimension(40, 40));
        btn30.setMinimumSize(new java.awt.Dimension(40, 40));
        btn30.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn30);
        btn30.setBounds(170, 10, 40, 40);

        btn31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn31.setBorder(null);
        btn31.setMaximumSize(new java.awt.Dimension(40, 40));
        btn31.setMinimumSize(new java.awt.Dimension(40, 40));
        btn31.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn31);
        btn31.setBounds(170, 50, 40, 40);

        btn32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn32.setBorder(null);
        btn32.setMaximumSize(new java.awt.Dimension(40, 40));
        btn32.setMinimumSize(new java.awt.Dimension(40, 40));
        btn32.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn32);
        btn32.setBounds(170, 90, 40, 40);

        btn33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn33.setBorder(null);
        btn33.setMaximumSize(new java.awt.Dimension(40, 40));
        btn33.setMinimumSize(new java.awt.Dimension(40, 40));
        btn33.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn33);
        btn33.setBounds(170, 130, 40, 40);

        btn34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn34.setBorder(null);
        btn34.setMaximumSize(new java.awt.Dimension(40, 40));
        btn34.setMinimumSize(new java.awt.Dimension(40, 40));
        btn34.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn34);
        btn34.setBounds(170, 170, 40, 40);

        btn35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn35.setBorder(null);
        btn35.setMaximumSize(new java.awt.Dimension(40, 40));
        btn35.setMinimumSize(new java.awt.Dimension(40, 40));
        btn35.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn35);
        btn35.setBounds(170, 210, 40, 40);

        btn36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn36.setBorder(null);
        btn36.setMaximumSize(new java.awt.Dimension(40, 40));
        btn36.setMinimumSize(new java.awt.Dimension(40, 40));
        btn36.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn36);
        btn36.setBounds(170, 250, 40, 40);

        btn37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn37.setBorder(null);
        btn37.setMaximumSize(new java.awt.Dimension(40, 40));
        btn37.setMinimumSize(new java.awt.Dimension(40, 40));
        btn37.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn37);
        btn37.setBounds(170, 290, 40, 40);

        btn38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn38.setBorder(null);
        btn38.setMaximumSize(new java.awt.Dimension(40, 40));
        btn38.setMinimumSize(new java.awt.Dimension(40, 40));
        btn38.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn38);
        btn38.setBounds(170, 330, 40, 40);

        btn40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn40.setBorder(null);
        btn40.setMaximumSize(new java.awt.Dimension(40, 40));
        btn40.setMinimumSize(new java.awt.Dimension(40, 40));
        btn40.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn40);
        btn40.setBounds(210, 10, 40, 40);

        btn41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn41.setBorder(null);
        btn41.setMaximumSize(new java.awt.Dimension(40, 40));
        btn41.setMinimumSize(new java.awt.Dimension(40, 40));
        btn41.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn41);
        btn41.setBounds(210, 50, 40, 40);

        btn42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn42.setBorder(null);
        btn42.setMaximumSize(new java.awt.Dimension(40, 40));
        btn42.setMinimumSize(new java.awt.Dimension(40, 40));
        btn42.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn42);
        btn42.setBounds(210, 90, 40, 40);

        btn43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn43.setBorder(null);
        btn43.setMaximumSize(new java.awt.Dimension(40, 40));
        btn43.setMinimumSize(new java.awt.Dimension(40, 40));
        btn43.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn43);
        btn43.setBounds(210, 130, 40, 40);

        btn44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn44.setBorder(null);
        btn44.setMaximumSize(new java.awt.Dimension(40, 40));
        btn44.setMinimumSize(new java.awt.Dimension(40, 40));
        btn44.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn44);
        btn44.setBounds(210, 170, 40, 40);

        btn45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn45.setBorder(null);
        btn45.setMaximumSize(new java.awt.Dimension(40, 40));
        btn45.setMinimumSize(new java.awt.Dimension(40, 40));
        btn45.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn45);
        btn45.setBounds(210, 210, 40, 40);

        btn46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn46.setBorder(null);
        btn46.setMaximumSize(new java.awt.Dimension(40, 40));
        btn46.setMinimumSize(new java.awt.Dimension(40, 40));
        btn46.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn46);
        btn46.setBounds(210, 250, 40, 40);

        btn47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn47.setBorder(null);
        btn47.setMaximumSize(new java.awt.Dimension(40, 40));
        btn47.setMinimumSize(new java.awt.Dimension(40, 40));
        btn47.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn47);
        btn47.setBounds(210, 290, 40, 40);

        btn48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn48.setBorder(null);
        btn48.setMaximumSize(new java.awt.Dimension(40, 40));
        btn48.setMinimumSize(new java.awt.Dimension(40, 40));
        btn48.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn48);
        btn48.setBounds(210, 330, 40, 40);

        btn50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn50.setBorder(null);
        btn50.setMaximumSize(new java.awt.Dimension(40, 40));
        btn50.setMinimumSize(new java.awt.Dimension(40, 40));
        btn50.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn50);
        btn50.setBounds(250, 10, 40, 40);

        btn51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn51.setBorder(null);
        btn51.setMaximumSize(new java.awt.Dimension(40, 40));
        btn51.setMinimumSize(new java.awt.Dimension(40, 40));
        btn51.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn51);
        btn51.setBounds(250, 50, 40, 40);

        btn52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn52.setBorder(null);
        btn52.setMaximumSize(new java.awt.Dimension(40, 40));
        btn52.setMinimumSize(new java.awt.Dimension(40, 40));
        btn52.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn52);
        btn52.setBounds(250, 90, 40, 40);

        btn53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn53.setBorder(null);
        btn53.setMaximumSize(new java.awt.Dimension(40, 40));
        btn53.setMinimumSize(new java.awt.Dimension(40, 40));
        btn53.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn53);
        btn53.setBounds(250, 130, 40, 40);

        btn54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn54.setBorder(null);
        btn54.setMaximumSize(new java.awt.Dimension(40, 40));
        btn54.setMinimumSize(new java.awt.Dimension(40, 40));
        btn54.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn54);
        btn54.setBounds(250, 170, 40, 40);

        btn55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn55.setBorder(null);
        btn55.setMaximumSize(new java.awt.Dimension(40, 40));
        btn55.setMinimumSize(new java.awt.Dimension(40, 40));
        btn55.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn55);
        btn55.setBounds(250, 210, 40, 40);

        btn56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn56.setBorder(null);
        btn56.setMaximumSize(new java.awt.Dimension(40, 40));
        btn56.setMinimumSize(new java.awt.Dimension(40, 40));
        btn56.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn56);
        btn56.setBounds(250, 250, 40, 40);

        btn57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn57.setBorder(null);
        btn57.setMaximumSize(new java.awt.Dimension(40, 40));
        btn57.setMinimumSize(new java.awt.Dimension(40, 40));
        btn57.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn57);
        btn57.setBounds(250, 290, 40, 40);

        btn58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn58.setBorder(null);
        btn58.setMaximumSize(new java.awt.Dimension(40, 40));
        btn58.setMinimumSize(new java.awt.Dimension(40, 40));
        btn58.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn58);
        btn58.setBounds(250, 330, 40, 40);

        btn60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn60.setBorder(null);
        btn60.setMaximumSize(new java.awt.Dimension(40, 40));
        btn60.setMinimumSize(new java.awt.Dimension(40, 40));
        btn60.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn60);
        btn60.setBounds(290, 10, 40, 40);

        btn61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn61.setBorder(null);
        btn61.setMaximumSize(new java.awt.Dimension(40, 40));
        btn61.setMinimumSize(new java.awt.Dimension(40, 40));
        btn61.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn61);
        btn61.setBounds(290, 50, 40, 40);

        btn62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn62.setBorder(null);
        btn62.setMaximumSize(new java.awt.Dimension(40, 40));
        btn62.setMinimumSize(new java.awt.Dimension(40, 40));
        btn62.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn62);
        btn62.setBounds(290, 90, 40, 40);

        btn63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn63.setBorder(null);
        btn63.setMaximumSize(new java.awt.Dimension(40, 40));
        btn63.setMinimumSize(new java.awt.Dimension(40, 40));
        btn63.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn63);
        btn63.setBounds(290, 130, 40, 40);

        btn64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn64.setBorder(null);
        btn64.setMaximumSize(new java.awt.Dimension(40, 40));
        btn64.setMinimumSize(new java.awt.Dimension(40, 40));
        btn64.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn64);
        btn64.setBounds(290, 170, 40, 40);

        btn65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn65.setBorder(null);
        btn65.setMaximumSize(new java.awt.Dimension(40, 40));
        btn65.setMinimumSize(new java.awt.Dimension(40, 40));
        btn65.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn65);
        btn65.setBounds(290, 210, 40, 40);

        btn66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn66.setBorder(null);
        btn66.setMaximumSize(new java.awt.Dimension(40, 40));
        btn66.setMinimumSize(new java.awt.Dimension(40, 40));
        btn66.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn66);
        btn66.setBounds(290, 250, 40, 40);

        btn67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn67.setBorder(null);
        btn67.setMaximumSize(new java.awt.Dimension(40, 40));
        btn67.setMinimumSize(new java.awt.Dimension(40, 40));
        btn67.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn67);
        btn67.setBounds(290, 290, 40, 40);

        btn68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn68.setBorder(null);
        btn68.setMaximumSize(new java.awt.Dimension(40, 40));
        btn68.setMinimumSize(new java.awt.Dimension(40, 40));
        btn68.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn68);
        btn68.setBounds(290, 330, 40, 40);

        btn70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn70.setBorder(null);
        btn70.setMaximumSize(new java.awt.Dimension(40, 40));
        btn70.setMinimumSize(new java.awt.Dimension(40, 40));
        btn70.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn70);
        btn70.setBounds(330, 10, 40, 40);

        btn71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn71.setBorder(null);
        btn71.setMaximumSize(new java.awt.Dimension(40, 40));
        btn71.setMinimumSize(new java.awt.Dimension(40, 40));
        btn71.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn71);
        btn71.setBounds(330, 50, 40, 40);

        btn72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn72.setBorder(null);
        btn72.setMaximumSize(new java.awt.Dimension(40, 40));
        btn72.setMinimumSize(new java.awt.Dimension(40, 40));
        btn72.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn72);
        btn72.setBounds(330, 90, 40, 40);

        btn73.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn73.setBorder(null);
        btn73.setMaximumSize(new java.awt.Dimension(40, 40));
        btn73.setMinimumSize(new java.awt.Dimension(40, 40));
        btn73.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn73);
        btn73.setBounds(330, 130, 40, 40);

        btn74.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn74.setBorder(null);
        btn74.setMaximumSize(new java.awt.Dimension(40, 40));
        btn74.setMinimumSize(new java.awt.Dimension(40, 40));
        btn74.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn74);
        btn74.setBounds(330, 170, 40, 40);

        btn75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn75.setBorder(null);
        btn75.setMaximumSize(new java.awt.Dimension(40, 40));
        btn75.setMinimumSize(new java.awt.Dimension(40, 40));
        btn75.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn75);
        btn75.setBounds(330, 210, 40, 40);

        btn76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn76.setBorder(null);
        btn76.setMaximumSize(new java.awt.Dimension(40, 40));
        btn76.setMinimumSize(new java.awt.Dimension(40, 40));
        btn76.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn76);
        btn76.setBounds(330, 250, 40, 40);

        btn77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn77.setBorder(null);
        btn77.setMaximumSize(new java.awt.Dimension(40, 40));
        btn77.setMinimumSize(new java.awt.Dimension(40, 40));
        btn77.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn77);
        btn77.setBounds(330, 290, 40, 40);

        btn78.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn78.setBorder(null);
        btn78.setMaximumSize(new java.awt.Dimension(40, 40));
        btn78.setMinimumSize(new java.awt.Dimension(40, 40));
        btn78.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn78);
        btn78.setBounds(330, 330, 40, 40);

        btn80.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn80.setBorder(null);
        btn80.setMaximumSize(new java.awt.Dimension(40, 40));
        btn80.setMinimumSize(new java.awt.Dimension(40, 40));
        btn80.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn80);
        btn80.setBounds(370, 10, 40, 40);

        btn81.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn81.setBorder(null);
        btn81.setMaximumSize(new java.awt.Dimension(40, 40));
        btn81.setMinimumSize(new java.awt.Dimension(40, 40));
        btn81.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn81);
        btn81.setBounds(370, 50, 40, 40);

        btn82.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn82.setBorder(null);
        btn82.setMaximumSize(new java.awt.Dimension(40, 40));
        btn82.setMinimumSize(new java.awt.Dimension(40, 40));
        btn82.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn82);
        btn82.setBounds(370, 90, 40, 40);

        btn83.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn83.setBorder(null);
        btn83.setMaximumSize(new java.awt.Dimension(40, 40));
        btn83.setMinimumSize(new java.awt.Dimension(40, 40));
        btn83.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn83);
        btn83.setBounds(370, 130, 40, 40);

        btn84.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn84.setBorder(null);
        btn84.setMaximumSize(new java.awt.Dimension(40, 40));
        btn84.setMinimumSize(new java.awt.Dimension(40, 40));
        btn84.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn84);
        btn84.setBounds(370, 170, 40, 40);

        btn85.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn85.setBorder(null);
        btn85.setMaximumSize(new java.awt.Dimension(40, 40));
        btn85.setMinimumSize(new java.awt.Dimension(40, 40));
        btn85.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn85);
        btn85.setBounds(370, 210, 40, 40);

        btn86.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn86.setBorder(null);
        btn86.setMaximumSize(new java.awt.Dimension(40, 40));
        btn86.setMinimumSize(new java.awt.Dimension(40, 40));
        btn86.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn86);
        btn86.setBounds(370, 250, 40, 40);

        btn87.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn87.setBorder(null);
        btn87.setMaximumSize(new java.awt.Dimension(40, 40));
        btn87.setMinimumSize(new java.awt.Dimension(40, 40));
        btn87.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn87);
        btn87.setBounds(370, 290, 40, 40);

        btn88.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn88.setBorder(null);
        btn88.setMaximumSize(new java.awt.Dimension(40, 40));
        btn88.setMinimumSize(new java.awt.Dimension(40, 40));
        btn88.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(btn88);
        btn88.setBounds(370, 330, 40, 40);

        jLabel00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel00);
        jLabel00.setBounds(50, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 10, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 50, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 50, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 50, 40, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 90, 40, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 90, 40, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 90, 40, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 130, 40, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 130, 40, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 130, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 170, 40, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(90, 170, 40, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(130, 170, 40, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 210, 40, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(90, 210, 40, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(130, 210, 40, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(50, 250, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(90, 250, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(130, 250, 40, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(50, 290, 40, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(90, 290, 40, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(130, 290, 40, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(50, 330, 40, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(90, 330, 40, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(130, 330, 40, 40);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel29);
        jLabel29.setBounds(170, 10, 40, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel30);
        jLabel30.setBounds(210, 10, 40, 40);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(250, 10, 40, 40);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(170, 50, 40, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel33);
        jLabel33.setBounds(210, 50, 40, 40);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel34);
        jLabel34.setBounds(250, 50, 40, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel35);
        jLabel35.setBounds(170, 90, 40, 40);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel36);
        jLabel36.setBounds(210, 90, 40, 40);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel37);
        jLabel37.setBounds(250, 90, 40, 40);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel38);
        jLabel38.setBounds(170, 130, 40, 40);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel39);
        jLabel39.setBounds(210, 130, 40, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel40);
        jLabel40.setBounds(250, 130, 40, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel41);
        jLabel41.setBounds(170, 170, 40, 40);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel42);
        jLabel42.setBounds(210, 170, 40, 40);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel43);
        jLabel43.setBounds(250, 170, 40, 40);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel44);
        jLabel44.setBounds(170, 210, 40, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel45);
        jLabel45.setBounds(210, 210, 40, 40);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel46);
        jLabel46.setBounds(250, 210, 40, 40);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel47);
        jLabel47.setBounds(170, 250, 40, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel48);
        jLabel48.setBounds(210, 250, 40, 40);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel49);
        jLabel49.setBounds(250, 250, 40, 40);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel50);
        jLabel50.setBounds(170, 290, 40, 40);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel51);
        jLabel51.setBounds(210, 290, 40, 40);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel52);
        jLabel52.setBounds(250, 290, 40, 40);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel53);
        jLabel53.setBounds(170, 330, 40, 40);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel54);
        jLabel54.setBounds(210, 330, 40, 40);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel55);
        jLabel55.setBounds(250, 330, 40, 40);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel56);
        jLabel56.setBounds(290, 10, 40, 40);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel57);
        jLabel57.setBounds(330, 10, 40, 40);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel58);
        jLabel58.setBounds(370, 10, 40, 40);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel59);
        jLabel59.setBounds(290, 50, 40, 40);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel60);
        jLabel60.setBounds(330, 50, 40, 40);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel61);
        jLabel61.setBounds(370, 50, 40, 40);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel62);
        jLabel62.setBounds(290, 90, 40, 40);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel63);
        jLabel63.setBounds(330, 90, 40, 40);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel64);
        jLabel64.setBounds(370, 90, 40, 40);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel65);
        jLabel65.setBounds(290, 130, 40, 40);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel66);
        jLabel66.setBounds(330, 130, 40, 40);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel67);
        jLabel67.setBounds(370, 130, 40, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel68);
        jLabel68.setBounds(290, 170, 40, 40);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel69);
        jLabel69.setBounds(330, 170, 40, 40);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel70);
        jLabel70.setBounds(370, 170, 40, 40);

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel71);
        jLabel71.setBounds(290, 210, 40, 40);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel72);
        jLabel72.setBounds(330, 210, 40, 40);

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel73);
        jLabel73.setBounds(370, 210, 40, 40);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-left.png"))); // NOI18N
        getContentPane().add(jLabel74);
        jLabel74.setBounds(290, 250, 40, 40);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-top.png"))); // NOI18N
        getContentPane().add(jLabel75);
        jLabel75.setBounds(330, 250, 40, 40);

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/top-right.png"))); // NOI18N
        getContentPane().add(jLabel76);
        jLabel76.setBounds(370, 250, 40, 40);

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-left.png"))); // NOI18N
        getContentPane().add(jLabel77);
        jLabel77.setBounds(290, 290, 40, 40);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle.png"))); // NOI18N
        getContentPane().add(jLabel78);
        jLabel78.setBounds(330, 290, 40, 40);

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-right.png"))); // NOI18N
        getContentPane().add(jLabel79);
        jLabel79.setBounds(370, 290, 40, 40);

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-left.png"))); // NOI18N
        getContentPane().add(jLabel80);
        jLabel80.setBounds(290, 330, 40, 40);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/middle-bottom.png"))); // NOI18N
        getContentPane().add(jLabel81);
        jLabel81.setBounds(330, 330, 40, 40);

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/bottom-right.png"))); // NOI18N
        getContentPane().add(jLabel82);
        jLabel82.setBounds(370, 330, 40, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudokuImages/water.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(600, 400));
        background.setMinimumSize(new java.awt.Dimension(600, 400));
        background.setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // 
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    // button quits sudoku game and displays the EndScreen
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI(finalScore).setVisible(true);
            }
        });
    }   
    
    public int getFinalScore() {
        return finalScore;
    }
    
    public void setScore(int finalScore) {
        String displayScore = Integer.toString(finalScore);
        scoreLabel.setText(displayScore);
    }
    
    public void endGame() {
        EndScreen endScreen = new EndScreen(getFinalScore());
        this.setVisible(false);
        endScreen.setScore(getFinalScore()); // changed to getFinalScore() instead of finalScore to properly pass argument
        endScreen.setVisible(true);
    }
    
    public static void generate() {
        int k=1,n=1;
        for(int i=0;i<9;i++) {
           k=n;
            for(int j=0;j<9;j++) {
                if(k<=9){
                    a[i][j]=k;
                    k++;
                }else{
                    k=1;
                    a[i][j]=k;
                    k++;
                }
            }
            n=k+3;
            if(k==10){
                n=4;
            }
            if(n>9) {
                n=(n%9)+1;
            }
        }   
    }
    public static void random_gen(int check){
        int k1,k2,max=2,min=0;
        Random r= new Random();
        for(int i=0;i<3;i++) { //There are three groups.So we are using for loop three times.
            k1=r.nextInt(max-min+1)+min; //This while is just to ensure k1 is not equal to k2.
            do{
                k2=r.nextInt(max-min+1)+min;
            }while(k1==k2);
            max+=3;min+=3; 
            if(check==1) {//calling a function to interchange the selected rows.
                permutation_row(k1,k2);
            } else if(check==0) {
                permutation_col(k1,k2);
            }
        }
    }
    public static void permutation_row(int k1,int k2){
        int temp;//k1 and k2 are two rows that we are selecting to interchange.
        for(int j=0;j<9;j++) {
            temp=a[k1][j];
            a[k1][j]=a[k2][j];
            a[k2][j]=temp;
        }
    }
    public static void permutation_col(int k1,int k2){
        int temp;
        for(int j=0;j<9;j++) {
            temp=a[j][k1];
            a[j][k1]=a[j][k2];
            a[j][k2]=temp;
        }
    }        
    public static void row_change(int k1,int k2) {
        int temp;
        for(int n=1;n<=3;n++) {
            for(int i=0;i<9;i++) {
                temp=a[k1][i];
                a[k1][i]=a[k2][i];
                a[k2][i]=temp;
            }
            k1++;
            k2++;
        }
    }
    public static void col_change(int k1,int k2) {
        int temp;
        for(int n=1;n<=3;n++) {
          for(int i=0;i<9;i++) {
                temp=a[i][k1];
                a[i][k1]=a[i][k2];
                a[i][k2]=temp;
            }
            k1++;
            k2++;
        }
    }
    public int rndmNumber(){
        Random rand = new Random();
        int  n = rand.nextInt(50) + 1;
        return n % 3;
    }
    public void setupSudoku() {
        generate();
        random_gen(1);
        random_gen(0);

        if (rndmNumber() == 1) {
        btn00.setText(Integer.toString(a[0][0]));
        }
        if (rndmNumber() == 1) {
        btn01.setText(Integer.toString(a[0][1]));
        }
        if (rndmNumber() == 1) {
        btn02.setText(Integer.toString(a[0][2]));
        }
        if (rndmNumber() == 1) {
        btn03.setText(Integer.toString(a[0][3]));
        }
        if (rndmNumber() == 1) {
        btn04.setText(Integer.toString(a[0][4]));
        }
        if (rndmNumber() == 1) {
        btn05.setText(Integer.toString(a[0][5]));
        }
        if (rndmNumber() == 1) {
        btn06.setText(Integer.toString(a[0][6]));
        }
        if (rndmNumber() == 1) {
        btn07.setText(Integer.toString(a[0][7]));
        }
        if (rndmNumber() == 1){
        btn08.setText(Integer.toString(a[0][8]));
        }
        
        if (rndmNumber() == 1) {
        btn10.setText(Integer.toString(a[1][0]));
        }
        if (rndmNumber() == 1) {
        btn11.setText(Integer.toString(a[1][1]));
        }
        if (rndmNumber() == 1) {
        btn12.setText(Integer.toString(a[1][2]));
        }
        if (rndmNumber() == 1) {
        btn13.setText(Integer.toString(a[1][3]));
        }
        if (rndmNumber() == 1) {
        btn14.setText(Integer.toString(a[1][4]));
        }
        if (rndmNumber() == 1) {
        btn15.setText(Integer.toString(a[1][5]));
        }
        if (rndmNumber() == 1) {
        btn16.setText(Integer.toString(a[1][6]));
        }
        if (rndmNumber() == 1) {
        btn17.setText(Integer.toString(a[1][7]));
        }
        if (rndmNumber() == 1) {
        btn18.setText(Integer.toString(a[1][8]));
        }
        
        
        if (rndmNumber() == 1) {
        btn20.setText(Integer.toString(a[2][0]));
        }
        if (rndmNumber() == 1) {
        btn21.setText(Integer.toString(a[2][1]));
        }
        if (rndmNumber() == 1) {
        btn22.setText(Integer.toString(a[2][2]));
        }
        if (rndmNumber() == 1) {
        btn23.setText(Integer.toString(a[2][3]));
        }
        if (rndmNumber() == 1) {
        btn24.setText(Integer.toString(a[2][4]));
        }
        if (rndmNumber() == 1) {
        btn25.setText(Integer.toString(a[2][5]));
        }
        if (rndmNumber() == 1) {
        btn26.setText(Integer.toString(a[2][6]));
        }
        if (rndmNumber() == 1) {
        btn27.setText(Integer.toString(a[2][7]));
        }
        if (rndmNumber() == 1) {
        btn28.setText(Integer.toString(a[2][8]));
        }
        
        
        if (rndmNumber() == 1) {
        btn30.setText(Integer.toString(a[3][0]));
        }
        if (rndmNumber() == 1) {
        btn31.setText(Integer.toString(a[3][1]));
        }
        if (rndmNumber() == 1) {
        btn32.setText(Integer.toString(a[3][2]));
        }
        if (rndmNumber() == 1) {
        btn33.setText(Integer.toString(a[3][3]));
        }
        if (rndmNumber() == 1) {
        btn34.setText(Integer.toString(a[3][4]));
        }
        if (rndmNumber() == 1) {
        btn35.setText(Integer.toString(a[3][5]));
        }
        if (rndmNumber() == 1) {
        btn36.setText(Integer.toString(a[3][6]));
        }
        if (rndmNumber() == 1) {
        btn37.setText(Integer.toString(a[3][7]));
        }
        if (rndmNumber() == 1) {
        btn38.setText(Integer.toString(a[3][8]));
        }

        
        if (rndmNumber() == 1) {
        btn40.setText(Integer.toString(a[4][0]));
        }
        if (rndmNumber() == 1) {
        btn41.setText(Integer.toString(a[4][1]));
        }
        if (rndmNumber() == 1) {
        btn42.setText(Integer.toString(a[4][2]));
        }
        if (rndmNumber() == 1) {
        btn43.setText(Integer.toString(a[4][3]));
        }
        if (rndmNumber() == 1) {
        btn44.setText(Integer.toString(a[4][4]));
        }
        if (rndmNumber() == 1) {
        btn45.setText(Integer.toString(a[4][5]));
        }
        if (rndmNumber() == 1) {
        btn46.setText(Integer.toString(a[4][6]));
        }
        if (rndmNumber() == 1) {
        btn47.setText(Integer.toString(a[4][7]));
        }
        if (rndmNumber() == 1) {
        btn48.setText(Integer.toString(a[4][8]));
        }
        

        if (rndmNumber() == 1) {
        btn50.setText(Integer.toString(a[5][0]));
        }
        if (rndmNumber() == 1) {
        btn51.setText(Integer.toString(a[5][1]));
        }
        if (rndmNumber() == 1) {
        btn52.setText(Integer.toString(a[5][2]));
        }
        if (rndmNumber() == 1) {
        btn53.setText(Integer.toString(a[5][3]));
        }
        if (rndmNumber() == 1) {
        btn54.setText(Integer.toString(a[5][4]));
        }
        if (rndmNumber() == 1) {
        btn55.setText(Integer.toString(a[5][5]));
        }
        if (rndmNumber() == 1) {
        btn56.setText(Integer.toString(a[5][6]));
        }
        if (rndmNumber() == 1) {
        btn57.setText(Integer.toString(a[5][7]));
        }
        if (rndmNumber() == 1) {
        btn58.setText(Integer.toString(a[5][8]));
        }
        

        if (rndmNumber() == 1) {
        btn60.setText(Integer.toString(a[6][0]));
        }
        if (rndmNumber() == 1) {
        btn61.setText(Integer.toString(a[6][1]));
        }
        if (rndmNumber() == 1) {
        btn62.setText(Integer.toString(a[6][2]));
        }
        if (rndmNumber() == 1) {
        btn63.setText(Integer.toString(a[6][3]));
        }
        if (rndmNumber() == 1) {
        btn64.setText(Integer.toString(a[6][4]));
        }
        if (rndmNumber() == 1) {
        btn65.setText(Integer.toString(a[6][5]));
        }
        if (rndmNumber() == 1) {
        btn66.setText(Integer.toString(a[6][6]));
        }
        if (rndmNumber() == 1) {
        btn67.setText(Integer.toString(a[6][7]));
        }
        if (rndmNumber() == 1) {
        btn68.setText(Integer.toString(a[6][8]));
        }
        

        if (rndmNumber() == 1) {
        btn70.setText(Integer.toString(a[7][0]));
        }
        if (rndmNumber() == 1) {
        btn71.setText(Integer.toString(a[7][1]));
        }
        if (rndmNumber() == 1) {
        btn72.setText(Integer.toString(a[7][2]));
        }
        if (rndmNumber() == 1) {
        btn73.setText(Integer.toString(a[7][3]));
        }
        if (rndmNumber() == 1) {
        btn74.setText(Integer.toString(a[7][4]));
        }
        if (rndmNumber() == 1) {
        btn75.setText(Integer.toString(a[7][5]));
        }
        if (rndmNumber() == 1) {
        btn76.setText(Integer.toString(a[7][6]));
        }
        if (rndmNumber() == 1) {
        btn77.setText(Integer.toString(a[7][7]));
        }
        if (rndmNumber() == 1) {
        btn78.setText(Integer.toString(a[7][8]));
        }
        

        if (rndmNumber() == 1) {
        btn80.setText(Integer.toString(a[8][0]));
        }
        if (rndmNumber() == 1) {
        btn81.setText(Integer.toString(a[8][1]));
        }
        if (rndmNumber() == 1) {
        btn82.setText(Integer.toString(a[8][2]));
        }
        if (rndmNumber() == 1) {
        btn83.setText(Integer.toString(a[8][3]));
        }
        if (rndmNumber() == 1) {
        btn84.setText(Integer.toString(a[8][4]));
        }
        if (rndmNumber() == 1) {
        btn85.setText(Integer.toString(a[8][5]));
        }
        if (rndmNumber() == 1) {
        btn86.setText(Integer.toString(a[8][6]));
        }
        if (rndmNumber() == 1) {
        btn87.setText(Integer.toString(a[8][7]));
        }
        if (rndmNumber() == 1) {
        btn88.setText(Integer.toString(a[8][8]));
        }
    }

// method: displayDateTime
    // purpose: display current time and date. Update each second.
    public void displayDateTimeSudoku() {
        final DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        ActionListener timerListener = new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                Date date = new Date();
                String time = timeFormat.format(date);
                dateTime.setText(dateFormat.format(date));
            }
        };
        Timer timer = new Timer(1000, timerListener);
        // to make sure it doesn't wait one second at the start
        timer.setInitialDelay(0);
        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField btn00;
    private javax.swing.JTextField btn01;
    private javax.swing.JTextField btn02;
    private javax.swing.JTextField btn03;
    private javax.swing.JTextField btn04;
    private javax.swing.JTextField btn05;
    private javax.swing.JTextField btn06;
    private javax.swing.JTextField btn07;
    private javax.swing.JTextField btn08;
    private javax.swing.JTextField btn10;
    private javax.swing.JTextField btn11;
    private javax.swing.JTextField btn12;
    private javax.swing.JTextField btn13;
    private javax.swing.JTextField btn14;
    private javax.swing.JTextField btn15;
    private javax.swing.JTextField btn16;
    private javax.swing.JTextField btn17;
    private javax.swing.JTextField btn18;
    private javax.swing.JTextField btn20;
    private javax.swing.JTextField btn21;
    private javax.swing.JTextField btn22;
    private javax.swing.JTextField btn23;
    private javax.swing.JTextField btn24;
    private javax.swing.JTextField btn25;
    private javax.swing.JTextField btn26;
    private javax.swing.JTextField btn27;
    private javax.swing.JTextField btn28;
    private javax.swing.JTextField btn30;
    private javax.swing.JTextField btn31;
    private javax.swing.JTextField btn32;
    private javax.swing.JTextField btn33;
    private javax.swing.JTextField btn34;
    private javax.swing.JTextField btn35;
    private javax.swing.JTextField btn36;
    private javax.swing.JTextField btn37;
    private javax.swing.JTextField btn38;
    private javax.swing.JTextField btn40;
    private javax.swing.JTextField btn41;
    private javax.swing.JTextField btn42;
    private javax.swing.JTextField btn43;
    private javax.swing.JTextField btn44;
    private javax.swing.JTextField btn45;
    private javax.swing.JTextField btn46;
    private javax.swing.JTextField btn47;
    private javax.swing.JTextField btn48;
    private javax.swing.JTextField btn50;
    private javax.swing.JTextField btn51;
    private javax.swing.JTextField btn52;
    private javax.swing.JTextField btn53;
    private javax.swing.JTextField btn54;
    private javax.swing.JTextField btn55;
    private javax.swing.JTextField btn56;
    private javax.swing.JTextField btn57;
    private javax.swing.JTextField btn58;
    private javax.swing.JTextField btn60;
    private javax.swing.JTextField btn61;
    private javax.swing.JTextField btn62;
    private javax.swing.JTextField btn63;
    private javax.swing.JTextField btn64;
    private javax.swing.JTextField btn65;
    private javax.swing.JTextField btn66;
    private javax.swing.JTextField btn67;
    private javax.swing.JTextField btn68;
    private javax.swing.JTextField btn70;
    private javax.swing.JTextField btn71;
    private javax.swing.JTextField btn72;
    private javax.swing.JTextField btn73;
    private javax.swing.JTextField btn74;
    private javax.swing.JTextField btn75;
    private javax.swing.JTextField btn76;
    private javax.swing.JTextField btn77;
    private javax.swing.JTextField btn78;
    private javax.swing.JTextField btn80;
    private javax.swing.JTextField btn81;
    private javax.swing.JTextField btn82;
    private javax.swing.JTextField btn83;
    private javax.swing.JTextField btn84;
    private javax.swing.JTextField btn85;
    private javax.swing.JTextField btn86;
    private javax.swing.JTextField btn87;
    private javax.swing.JTextField btn88;
    private javax.swing.JLabel dateTime;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
